name: Ping Render Website

on:
  schedule:
    - cron: "*/5 * * * *"  # Ping mỗi 5 phút
  workflow_dispatch:       # Cho phép chạy thủ công

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Gửi GET request đến website Laravel trên Render
        run: curl -s https://paraline-huanpn-oyasumi.onrender.com
        
